
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: better_boards_development

test:
  <<: *default
  database: better_boards_test

production:
  adapater: postgresql
  encoding: unicode
  database: better_board_production
