# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8538b521c9439a4d35f1816f754531cdcd7080b6d20fd72b904ab1915883999c3c370bb90725acae5172e520dd75b8d3ca75032c85d9d1599b7aec72f503d2c9

test:
  secret_key_base: f86a925e6aa1630488f1c40a2dcb1581a68ef91b8158e93feb36eaa7f7217283e52732f04340c196d6942b5297eb1352c42ebc835f463bcf4f54a036334656dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
